services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
